### ISSUE TITLE
Fails for http://www.imdb.com/title/tt0117500/

### ISSUE THREAD

**Issue by davidrecordon** [scottmac/opengraph#1]
__values seems to be empty in line:
    if (empty($page->_values)) { return false; }

**Comment by scottmac** [comment]
IMDB is using
<meta name="og:title"
The spec says
<meta property="og:title"

So is IMDB broken or not?

**Comment by scottmac** [comment]
They're also missing og:image and og:type which are required.

**Comment by davidrecordon** [comment]
Yeah, they're broken. Ignore my use case.

**Comment by scottmac** [comment]
It's on the main open graph protocol site, maybe we should use Rotten Tomato as an example :)
