### ISSUE TITLE
How do you echo just the og:image link?

### ISSUE THREAD

**Issue by berdesos** [scottmac/opengraph#26]
Very useful library!
How do you echo just the og:image link though?
Thank you

**Comment by berdesos** [comment]
To answer my own question:

<?php
require_once('OpenGraph.php');

$graph = OpenGraph::fetch('http://www.rottentomatoes.com/m/10011268-oceans/');
$image_url = $graph->image;
echo $image_url;
?>

**Comment by degtyaryov** [comment]
How echo og:image:type ??
